config/routes.rb
Rails.application.routes.draw do
  root :to => 'user_sessions#logged_or_not'
  put 'set_current_category' => 'users#set_current_category'
  get 'home' => 'dashboard/cards#home'
  get 'login' => 'user_sessions#new'
  post 'logout' => 'user_sessions#destroy'
  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github
  get "oauth/:provider" => "oauths#oauth", as: :auth_at_provider
  get 'oauths/oauth'
  get 'oauths/callback'
  resources :user_sessions

  namespace :dashboard do
    resources :categories
    resources :users do
      resources :cards do
        member do
          post 'review'
        end
      end
    end
  end


end

app/views/welcome/index.html.erb
<section id="container">
  <section>
    <div class="hero-unit">
      <h1>Флэшкарточкер</h1>
      <p style="font-size: 22px;">
        Первый в мире удобный менеджер флеш-карточек. Именно так.
      </p>
    </div>
    <div id='content'>
      <ul class="nav nav-pills" >
        <li><%= link_to "Добавить категорию", new_category_path %></li>
        <li><%= link_to "Все категории", categories_path %></li>
        <li style="float: right"><%= link_to "Все карточки", user_cards_path(current_user) %></li>
      </ul>
          <!-- Если карточки есть, то выводим форму -->
      <% if @card %>
        <div id="card_index">
          <p id="category">
            Категория: 
            <%= @card.category.name %>
          </p>
          <p id="card_img_p">
            <%= image_tag @card.picture.url(:medium) %> 
          </p>
          <p id='index_form'>
            <%= @card.original_text %>
          </p>
        </div>
        <%= form_tag(review_user_card_path(current_user, @card), class: "form-horizontal", id: "form_translate")  do %>
          <%= hidden_field_tag :timer_value %>
          <%= label_tag :label, "Введите перевод:" %>
          <%= text_field_tag :translated_text %>
          <%= submit_tag "Проверить", class: "btn btn-primary" %>
        <% end %>
        <% if flash[:translation_status] == 'false' %>
          <div class="alert alert-error">Неверно!</div> 
        <% elsif flash[:translation_status] == 'true' %>
          <div class="alert alert-success">Верно! Следующая карточка</div>
        <% end %>
        <span class="error"><%= flash[:misprint] %></span> 
      <% else %>
        <span class="error">Непросмотренных карточек нет</span>
      <% end %>
    </div>
  <div id="footer">
    <div class="container">
    <p id="credit">My Ruby On Rails project 2014</p>
  </div> 
  </section>
</section>