config/routes.rb
Rails.application.routes.draw do
  root :to => 'user_sessions#logged_or_not'
  put 'set_current_category' => 'users#set_current_category'
  get 'home' => 'dashboard/cards#home'
  get 'login' => 'user_sessions#new'
  post 'logout' => 'user_sessions#destroy'
  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github
  get "oauth/:provider" => "oauths#oauth", as: :auth_at_provider
  get 'oauths/oauth'
  get 'oauths/callback'
  resources :user_sessions

  namespace :dashboard do
    resources :categories
    resources :users do
      resources :cards do
        member do
          post 'review'
        end
      end
    end
  end


end

app/models/card.rb
require 'secretkeymanager' #модуль для выгрузки паролей из yml-файлы
class Card < ActiveRecord::Base
  
  
  belongs_to :user
  belongs_to :category
  
  has_attached_file :picture, styles: { medium: "360x360>", thumb: "100x100>" },
    default_url: "http://s3.amazonaws.com/#{ SecretKeyManager.config('aws')['bucket'] }/missing_:style.png",
    storage: :s3,
    s3_credentials: S3_CREDENTIALS
  
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/
  validates_attachment_size :picture, less_than: 2.megabytes
  validates :original_text, 
            :translated_text, 
            :review_date, 
            :user_id, 
            :category_id, presence: true
            
  # скоуп позволяет выделить часто использованные запросы и поместить их в метод
  scope :review_before, ->(date) { where("review_date <= ?", date).order('RANDOM()') }

  def check_translation(translation, timer)
    @timer = timer.to_i
    levenshtein_check_result = levenshtein_check(translation)
    case levenshtein_check_result
    when :success
      update_review_attributes(@timer, true)
    when :misprint
      increment(:number_of_misprint)
      save
    when :fail
      update_review_attributes(@timer, false)
    end
    return levenshtein_check_result
  end
  
  def update_review_attributes(timer, translation_succeed)
    supermemo = SuperMemo.new(number_of_right, number_of_misprint, interval, efactor, timer, translation_succeed)  
    review_attributes = { 
                          interval: supermemo.interval,
                          efactor: supermemo.efactor,
                          number_of_review: number_of_review + 1 
                        }
    if translation_succeed
      review_attributes.update(number_of_misprint: 0, number_of_right: number_of_right + 1, review_date: Date.today + supermemo.interval)
    else
      review_attributes.update(number_of_right: 0, number_of_misprint: 0, review_date: Date.today)     
    end
    update_attributes(review_attributes)
  end

private

def levenshtein_check(translation)
    case Levenshtein.distance(translation, translated_text)
    when 0
      :success
    when 1, 2
      :misprint
    else
      :fail
    end
  end

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  # метод before_action добавляет срабатывание метода find_card 
  skip_before_action :require_login, only: :logged_or_not
  before_action :find_card, except: [:new, :create, :index, :home, :logged_or_not]
  
  def logged_or_not
    if logged_in?
      redirect_to home_path
    else
      render 'logged_or_not'
    end
  end

  def new
    # добавили, чтобы при отображении вьюхи new @cards не был nil 
    # и не вылетало ошибки на if @cards.errors.any
    @card = current_user.cards.new
  end
  
  def home
    if params[:card_id]
      @card = current_user.cards.find(params[:card_id])
    else
      @card = current_user.pending_cards.first
    end
  end

  def index
   @cards = current_user.cards.all
  end
  
  def create
   # создаем запись из тех параметров, которые разрешили передавать
   @card = current_user.cards.new(card_params) 
   # сохраняем запись в базу
   if @card.save
     # идем в представление show
     redirect_to user_card_path(current_user, @card)
   else
    # если не сработало, то перегружаем представление
    render 'new' 
   end 
  end
  
  # ищем в базе запись по id и выводим в представлении show
  def show
  end

  def edit
  end
  
  def update
    if @card.update(card_params)
      redirect_to user_cards_path
    else
      render 'edit'
    end
  end

  def destroy
    @card.destroy
    redirect_to user_cards_path 
  end

  def review
    @result = @card.check_translation(params[:translated_text], params[:timer_value])
    @card = current_user.pending_cards.first
    respond_to do |format|
      format.js
    end
  end


private
  # определяем те параметры, которые можно передавать в метод контроллера create
  def card_params 
    params.require(:card).permit(:original_text, :translated_text, :review_date, :picture, :category_id)
  end
  # метод для before_action
  def find_card
    @card = current_user.cards.find(params[:id])
  end 
end

app/controllers/dashboard/cards_controller.rb
class Dashboard::CardsController < Dashboard::BaseController
  
  # метод before_action добавляет срабатывание метода find_card 
  before_action :find_card, except: [:new, :create, :index, :home]

  def new
    # добавили, чтобы при отображении вьюхи new @cards не был nil 
    # и не вылетало ошибки на if @cards.errors.any
    @card = current_user.cards.new
  end
  
  def home
    @card = current_user.pending_cards.first
  end

  def index
   @cards = current_user.cards.all
  end
  
  def create
   # создаем запись из тех параметров, которые разрешили передавать
   @card = current_user.cards.new(card_params) 
   # сохраняем запись в базу
   if @card.save
     # идем в представление show
     redirect_to dashboard_user_card_path(current_user, @card)
   else
    # если не сработало, то перегружаем представление
    render 'new' 
   end 
  end
  
  # ищем в базе запись по id и выводим в представлении show
  def show
  end

  def edit
  end
  
  def update
    if @card.update(card_params)
      redirect_to dashboard_user_cards_path
    else
      render 'edit'
    end
  end

  def destroy
    @card.destroy
    redirect_to dashboard_user_cards_path 
  end

  def review
    @result = @card.check_translation(params[:translated_text], params[:timer_value])
    @card = current_user.pending_cards.first
    respond_to do |format|
      format.js
    end
  end


private
  # определяем те параметры, которые можно передавать в метод контроллера create
  def card_params 
    params.require(:card).permit(:original_text, :translated_text, :review_date, :picture, :category_id)
  end
  # метод для before_action
  def find_card
    @card = current_user.cards.find(params[:id])
  end 
end

app/views/cards/_card.html.erb
<p id="category">
  Категория: 
  <%= card.category.name %>
</p>
<p id="card_img_p">
  <%= image_tag card.picture.url(:medium) %> 
</p>
<p id='index_form'>
  <%= card.original_text %>
</p>
<%= form_tag(review_user_card_path(current_user, @card), class: "form-horizontal", id: "form_translate", remote: true)  do %>
  <%= hidden_field_tag :timer_value %>
  <%= label_tag :label, "Введите перевод:" %>
  <%= text_field_tag :translated_text %>
  <%= submit_tag "Проверить", class: "btn btn-primary" %>
<% end %>

app/views/cards/_form.html.erb
<% if @card.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@card.errors.count, "error") %> prohibited
    this article from being saved:</h2>
    <ul>
      <% @card.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
     </ul>
  </div>
  </br>
<% end %>
<%= simple_form_for([current_user, @card]) do |f| %>
  <%= f.input :picture, label: 'Include Picture' %>
  <%= f.input :original_text, label: 'Original Text'  %>
  <%= f.input :translated_text, label: 'Translated Text' %>
  <%= f.association :category, 
                    include_blank: false, 
                    collection: current_user.categories, 
                    selected: params[:category_id] %>
  <%= f.input :review_date, label: 'Дата просмотра' %>
  <%= f.button :submit %>
<% end %>
<%= link_to "Home", root_path %>  
</section>

app/views/cards/home.html.erb
<section id="container">
  <section>
    <div class="hero-unit">
      <h1>Флэшкарточкер</h1>
      <p style="font-size: 22px;">
        Первый в мире удобный менеджер флеш-карточек. Именно так.
      </p>
    </div>
    <div id='menu'>
      <ul class="nav nav-pills" >
        <li><%= link_to "Добавить категорию", new_category_path %></li>
        <li><%= link_to "Все категории", categories_path %></li>
        <li style="float: right"><%= link_to "Все карточки", user_cards_path(current_user) %></li>
      </ul>
    </div>
    <div id='content'>
          <!-- Если карточка есть, то выводим её -->
      <% if @card %>
        <div id="card_index">
          <p id="category">
            Категория: 
            <%= @card.category.name %>
          </p>
          <p id="card_img_p">
            <%= image_tag @card.picture.url(:medium) %> 
          </p>
          <p id='index_form'>
            <%= @card.original_text %>
          </p>
          <%= form_tag(review_user_card_path(current_user, @card), class: "form-horizontal", id: "form_translate", remote: true)  do %>
            <%= hidden_field_tag :timer_value %>
            <%= label_tag :label, "Введите перевод:" %>
            <%= text_field_tag :translated_text %>
            <%= submit_tag "Проверить", class: "btn btn-primary" %>
          <% end %>
        </div>
      <% else %>
        <span class="no_more_cards">Непросмотренных карточек нет</span>
      <% end %>   
    </div>
  <div id="footer">
    <div class="container">
    <p id="credit">My Ruby On Rails project 2014</p>
  </div> 
  </section>
</section>

app/views/cards/index.html.erb
<section id="container">
  <h1>All Cards</h1>
  <table class="table table-striped" id='all_card_table'>
    <tr>
      <th>Picture</th>
      <th>Категория</th>
      <th>Original Text</th>
      <th>Translated Text</th>
      <th>Дата просмора</th>
      <th colspan="6"></th>
    <tr>
    <% @cards.each do |card| %>
      <tr>
        <td><%= image_tag card.picture.url(:thumb) %></td>
        <% if card.category %>
          <td><%= card.category.name %> </td>
        <% else %>
          <td><%= 'Без категории' %> </td>
        <% end %>
        <td><%= card.original_text %> </td>
        <td><%= card.translated_text %> </td>
        <td><%= card.review_date.strftime("%d/%m/%Y")  %> </td>
        <td><%= link_to 'Показать', user_card_path(current_user, card) %></td>
        <td><%= link_to 'Редактировать', edit_user_card_path(current_user, card) %></td>
        <td><%= link_to 'Удалить', user_card_path(current_user, card), method: :delete, data: { confirm: 'Вы уверены?' } %></td>
      </tr>
    <% end %>
  </table>
  <br>
  <%= link_to "Home", root_path %>
 </section>

app/views/cards/logged_or_not.html.erb
<section id="container">
  <header class="clearfix">
    <h2>Проект Флешкарточкер. Необходимо <%= link_to "войти", login_path %>
        в приложение или <%= link_to "зарегистрироваться", new_user_path %></h2>
    <ul class="nav nav-pills" >
      <li><%= link_to 'Login with Facebook', auth_at_provider_path(provider: :facebook) %></li>
      <li><%= link_to 'Login with Twitter', auth_at_provider_path(provider: :twitter) %></li>
    </ul>
  </header>
</section>

app/views/cards/review.js.erb
$("div.alert").remove();
$("span.error").remove();
<% if @result == :success %>
  <% if @card %>
    $("#form_translate").remove();
    $("#card_index").html("<%= j render 'cards/card', card: @card %>");
    $("#content").append("<div class='alert alert-success'>Верно! Следующая карточка</div>");
  <% else %>
    $("#content").html("<%= j render 'cards/no_more_cards'  %>");
  <% end %>
<% elsif @result == :misprint %>
  $("#content").append("<span class='no_more_cards'>Опечатка. Вы написали <%= params[:translated_text] %>, а надо <%= @card.translated_text %></span>");
<% else %>
  $("#content").append("<div class='alert alert-error'>Неверно!</div>");
<% end %>

app/views/cards/show.html.erb
<section id="container">
  <h1>This is <%= "Card№ #{@card.id}" %> </h1>
  <%= image_tag @card.picture.url(:medium) %>
  <table class="table">
    <tr>
      <th>Category</th>
      <th>Original Text</th>
      <th>Translated Text</th>
      <th>Created At</th>
      
    <tr>
      <tr>
        <td><%= @card.category.name %> </td>
        <td><%= @card.original_text %> </td>
        <td><%= @card.translated_text %> </td>
        <td><%= @card.review_date.strftime("%d/%m/%Y") %> </td> 
      </tr>
  </table>
  <br>
  <%= link_to "Home", root_path %>
  | <%= link_to 'Edit', edit_user_card_path(current_user, @card) %>
 </section>