config/routes.rb
Rails.application.routes.draw do
  root :to => 'user_sessions#logged_or_not'
  put 'set_current_category' => 'users#set_current_category'
  get 'home' => 'dashboard/cards#home'
  get 'login' => 'user_sessions#new'
  post 'logout' => 'user_sessions#destroy'
  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github
  get "oauth/:provider" => "oauths#oauth", as: :auth_at_provider
  get 'oauths/oauth'
  get 'oauths/callback'
  resources :user_sessions

  namespace :dashboard do
    resources :categories
    resources :users do
      resources :cards do
        member do
          post 'review'
        end
      end
    end
  end


end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, :about, :user_id, presence: true
  
  has_many :cards
  belongs_to :user
  
  #Callback. Перед тем, как добавить новый объект в таблицу меняет его параметры
  before_create :set_default_attributes

private
  
  def set_default_attributes
    self.name = name.capitalize
    self.about = about.capitalize
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :find_category, except: [:new, :create, :index]
  
  def new
    @category = current_user.categories.new
  end
  
  def index
    @categories = current_user.categories.order('name')
  end

  def create
    @category = current_user.categories.new(category_params)
    if @category.save
      flash[:success] = 'Карточка успешно добавлена'
      redirect_to root_path(@category)
    else
      flash[:error] = 'Что-то пошло не так'
      render 'new'
    end 
  end
  
  def edit 
  end

  def update
    if @category.update(category_params)
      redirect_to categories_path
    else
      render 'edit'
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path
  end
  
private
  
  def category_params 
    params.require(:category).permit(:name, :about)
  end

  def find_category
    @category = current_user.categories.find(params[:id])
  end

end

app/controllers/dashboard/categories_controller.rb
class Dashboard::CategoriesController < Dashboard::BaseController

  before_action :find_category, except: [:new, :create, :index]
  
  def new
    @category = current_user.categories.new
  end
  
  def index
    @categories = current_user.categories.order('name')
  end

  def create
    @category = current_user.categories.new(category_params)
    if @category.save
      flash[:success] = 'Карточка успешно добавлена'
      redirect_to root_path(@category)
    else
      flash[:error] = 'Что-то пошло не так'
      render 'new'
    end 
  end
  
  def edit 
  
  end

  def update
    if @category.update(category_params)
      redirect_to dashboard_categories_path
    else
      render 'edit'
    end
  end

  def destroy
    @category.destroy
    redirect_to dashboard_categories_path
  end
  
private
  
  def category_params 
    params.require(:category).permit(:name, :about)
  end

  def find_category
    @category = current_user.categories.find(params[:id])
  end

end

app/views/categories/_form.html.erb
<% if @category.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@category.errors.count, "error") %> prohibited
    this category from being saved:</h2>
    <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
     </ul>
  </div>
  </br>
<% end %>
<%= simple_form_for @category do |f| %>
  <%= f.input :name, label: 'Название' %>
  <%= f.input :about, label: 'Описание'  %>
  <%= f.button :submit, label: 'Добавить' %>
<% end %>
<%= link_to "Home", root_path %>  

app/views/categories/index.html.erb
<section id="container">
  <h1>Список категорий</h1>
  <table class="table table-striped">
    <tr>
      <th>Категория</th>
      <th>Описание</th>
      <th colspan="4"></th>
    <tr>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %> </td>
        <td><%= category.about %> </td>
        <td><%= link_to 'Добавить карточку', new_user_card_path(current_user, category_id: category) %></td>
        <td><%= link_to 'Активировать', set_current_category_path(category_id: category), method: :put %></td>
        <td><%= link_to 'Редактировать', edit_category_path(category) %></td>
        <td><%= link_to 'Удалить', category_path(category), method: :delete, data: { confirm: 'Вы уверены?' } %></td>
      </tr>
    <% end %>
  </table>
  <br>
  <%= link_to "Home", root_path %>
 </section>