config/routes.rb
Rails.application.routes.draw do
  root :to => 'user_sessions#logged_or_not'
  put 'set_current_category' => 'users#set_current_category'
  get 'home' => 'dashboard/cards#home'
  get 'login' => 'user_sessions#new'
  post 'logout' => 'user_sessions#destroy'
  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github
  get "oauth/:provider" => "oauths#oauth", as: :auth_at_provider
  get 'oauths/oauth'
  get 'oauths/callback'
  resources :user_sessions

  namespace :dashboard do
    resources :categories
    resources :users do
      resources :cards do
        member do
          post 'review'
        end
      end
    end
  end


end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_action :require_login, only: [:destroy]

  def logged_or_not
    if logged_in?
      redirect_to home_path
    else
      render 'logged_or_not'
    end
  end

  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to home_path, notice: "Login successful"
    else
      flash.now[:alert] = 'Login failed'
      render :new
    end
  end
  
  def destroy
    logout
    redirect_to root_path, notice: 'Logged out'
  end
end

app/views/user_sessions/_form.html.erb
<section id="container">
  <%= form_tag user_sessions_path, method: :post do %>
    <div class="field">
      <%= label_tag :email %><br />
      <%= text_field_tag :email %>
    </div>
    <div class="field">
      <%= label_tag :password %><br />
      <%= password_field_tag :password %>
    </div>
    <div class="actions">
      <%= submit_tag "Login" %>
    </div>
  <% end %>
</section>

app/views/user_sessions/logged_or_not.html.erb
<section id="container">
  <header class="clearfix">
    <h2>Проект Флешкарточкер. Необходимо <%= link_to "войти", login_path %>
        в приложение или <%= link_to "зарегистрироваться", new_dashboard_user_path %></h2>
    <ul class="nav nav-pills" >
      <li><%= link_to 'Login with Facebook', auth_at_provider_path(provider: :facebook) %></li>
      <li><%= link_to 'Login with Twitter', auth_at_provider_path(provider: :twitter) %></li>
    </ul>
  </header>
</section>

app/views/user_sessions/new.html.erb
<section id="container">
  <h1>Login</h1>
  <%= render 'form' %>
  <%= link_to 'Back', root_path %>
</section>